### ISSUE TITLE
You may want to make this repo private

### ISSUE THREAD

**Issue by ccozianu** [smeruelo/mooc-ocaml#3]
Hi Sonia,

I stumbled on this repo by searching in google for print_hash 
https://www.google.com/search?q=ocaml+%22print_hash%22
2nd result for me.

I think it could be even literally the course policy ( i  not sure about that, but likely as a nice thing to do for the instructors, you may want to make this project github private, so it's not discover-able by students.

Cheers,
Costin

**Comment by smeruelo** [comment]
Thank you for your concern, but this repository is public on purpose.
